steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/amrulla/resume:$BUILD_ID:$BUILD_ID', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/amrulla/resume:$BUILD_ID']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'amrulla-com', '--image', 'gcr.io/amrulla/resume:$BUILD_ID', '--region', 'asia-south1', '--platform', 'managed']
images:
- gcr.io/amrulla/resume:$BUILD_ID
